name: scrumlab_system_shortcuts
description: ANDROID & IOS flutter plugin to use system shortcuts like pressing home, back, volume Up, volume Down keys and toggle wifi, and bluetooth as well.
version: 2.1.0
homepage: https://github.com/scrum-lab/ScrumlabSystemShortcutsFlutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.scrumlab.scrumlabsystemshortcuts
        pluginClass: ScrumlabSystemShortcutsPlugin
      ios:
        pluginClass: ScrumlabSystemShortcutsPlugin
